#!/usr/bin/python
"""
Creates the sets for uploaded photos
"""
import logging
import os
import shelve
import sys

import flickrapi

import f2flickr.configuration as configuration

SET_DESC = 'auto generated by folders2flickr'

def print_xml_node(o):
    seqs = tuple, list, set, frozenset
    if isinstance(o, seqs):
        sys.stdout.write('[ ')
        for e in o: print_xml_node(e)
        sys.stdout.write(' ] ')
    elif isinstance(o, flickrapi.xmlnode.XMLNode):
        sys.stdout.write('{ ')
        for i in dir(o): 
            if not ( i.startswith('_') or i == 'name' or i == 'xml' ) :
                e = getattr(o, i)
                sys.stdout.write(str(i) + ' : ') 
                print_xml_node(e)
                sys.stdout.write(', ') 
        sys.stdout.write(' }')
    else:
        sys.stdout.write(str(o))


def _creatSet(flickr, photoSet, setName, existingSets):
    """
    Creates or updates a set on flickr with the given photos.
    """
    setName = setName.replace('\\',' ')
    setName = setName.replace('/',' ')
    setName = setName.strip()
    photos = [] #real photo objects
    for photo in photoSet:
        #photos.append(flickr.Photo(id = photo))
        photos.append(int(photo))

    fset = None
    # Ensure the desired set name isn't empty
    if not setName:
        return fset
    
    #unicodeSetName = setName.decode(sys.getfilesystemencoding())
	#Python3 does not need to decode
    unicodeSetName = setName
    #print ("Not decoding: ", unicodeSetName)
    #check if set with the name exists already
    generate = 'Generating'
    for existingSet in existingSets:
        if existingSet.title[0] == unicodeSetName:
            fset = existingSet
            logging.debug('tags2set: Found existing set %s', setName)
            generate = 'Updating'
            break
    msg = "%s set %s with %d pictures" % (generate, setName, len(photoSet))
    logging.debug(msg)
    print (msg)
    try:
        if(fset == None):
            logging.debug("tags2set: create set %s with photo %s",
                          setName, photos[0])
            resp = flickr.photosets.create(
                primary_photo_id=photos[0], title=setName, description=SET_DESC)
            fset = resp.photoset[0]
            logging.debug('tags2set: created new set %s', setName)
    except Exception as ex:
        logging.error('tags2set: Cannot create set "%s"', setName)
        logging.error(str(ex))
        logging.error(sys.exc_info()[0])
        return None

    print_xml_node(fset)
    

    try:
        flickr.photosets.editPhotos(
            photoset_id = fset['id'], primary_photo_id=photos[0], 
            photo_ids=','.join([str(photo) for photo in photos]))
    except Exception as ex:
        logging.error('tags2set: Cannot edit set %s', setName)
        logging.error(str(ex))
        logging.error(str(sys.exc_info()))
        return None


    logging.debug('tags2set: ...added %d photos', len(photos))
    return fset

def image2set(image):
    """
    Get the set name for a given image path
    """
    # if true, Set name is the name of the last subfolder
    onlysubs = configuration.configdict.get('only_sub_sets')
    if onlysubs.startswith('true'):
        _, setname = os.path.split(os.path.dirname(image))
    else:
        #set name is really a directory
        setname = os.path.dirname(image)
    return setname

def createSets(flickr, uploadedNow, historyFile):
    """
    Create/update all sets for the photos just uploaded
    """
    logging.debug('tags2set: Started tags2set')
    try:
        existingSets = flickr.photosets.getList()
        existingSets = existingSets.photosets[0].photoset
    except:
        logging.error("createSets error logging in/getPhotosets")
        logging.error(sys.exc_info()[0])
        return None

    uploaded = shelve.open( historyFile )
    #keys = uploaded.keys()
    #keys.sort()
    keys = sorted(uploaded.keys())
    uploadedSets = set()
    for uploadedid in uploadedNow:
        try:
            image = uploaded[str(uploadedid)]
        except KeyError:
            continue
        uploadedSets.add(image2set(image))

    lastSetName = ''
    photoSet = []
    createdSets = set()
    setName = ''
    for image in keys:
        if image.find(os.path.sep) == -1: #filter out photoid keys
            continue
        setName = image2set(image)
        # only update sets that have been modified this round
        if setName not in uploadedSets:
            continue

        if (not lastSetName == setName and not lastSetName == ''):
            #new set is starting so save last
            newset = _creatSet(flickr, photoSet, lastSetName, existingSets)
            if newset:
                existingSets.append(newset)
            createdSets.add(lastSetName)
            photoSet = []
        logging.debug("tags2set: Adding image %s", image)
        photoSet.append(uploaded.get(image)[0])
        lastSetName = setName

    #existing = set([setentry.title for setentry in existingSets])
    existing = set([setentry.title[0] for setentry in existingSets])
    for uploadedSet in uploadedSets:
        if uploadedSet not in existing or uploadedSet not in createdSets:
            _creatSet(flickr, [uploaded.get(photo)[0] for photo in keys if (
                            photo.find(os.path.sep) != -1
                            and image2set(photo) == uploadedSet)],
                uploadedSet, existingSets)
            createdSets.add(uploadedSet)
